### ISSUE TITLE
Need a better algorithm

### ISSUE THREAD

**Issue by dabaitu** [dabaitu/300#6]
For this problem: https://github.com/dabaitu/300/tree/master/math/mostPopulatedLine

Currently it's brute force which is O(n^3)

**Comment by cmooney3** [comment]
I'm fairly sure it can be done is O(n^2) like this, does it seem right?

lines = []

# Count how many times you generate the same lines when going through
# each pair of points. O(n^2)
for each pair of points p1, p2:
  new_line = Line(p1, p2)
  lines[new_line] = lines.get(new_line, 0) + 1

# Find the line with the most counts O(n^2)
best_line = lines[0]
for line in lines:
  if lines[line] > lines[best_line]:
    best_line = line

return best_line

I *think* there's a better solution, too actually.  I feel like there was some way to do it using an extra dimension or something actually.  Like extending the points into lines and then finding a plane that intersect them or something.  However I can't remember/think of how it would work really :(

This seems like it'd work for O(n^2) though, right?

**Comment by dabaitu** [comment]
Will modify to your suggestion. I didn't think of just sort the lines. Cool.
