### ISSUE TITLE
Is there a way to do this without modifying the original list?

### ISSUE THREAD

**Issue by cmooney3** [dabaitu/300#8]
https://github.com/dabaitu/300/blob/master/math/RandomSelectionFromArray/python/solution.py

I can do it a number of ways, but this is the only O(n) solution I've been able to think of.  It works in-place which is great, but it rearranges the original list.  Is there a way to do this with O(1) memory and maintaining the original list un-modified.

I've thought of a (rather convoluted) O(m^2) soution that only used O(m) memory, which may or may not be better than O(n) depending on how much bigger n is than m, but it's not a clear win...

**Comment by quinnbaetz** [comment]
Not O(1) memory, but what if you just copy the list before hand and do an in place sort then it would have O(n) memory and O(m) time complexity (better than O(m^2) and O(m) memory.

**Comment by shuoh** [comment]
I think an O(n) random-shuffle is essentially the solution to a specific case of the origin problem where m = n, and therefore should not be used to construct a solution to the problem in a more generic form.

Can we simply stash the randomly selected element to either end of the array, and reduce the scope of random selection after each iteration. Would this work?
<pre>
for i = 0:m-1
  r = random(i, n - 1) // random(a, b) returns a random number between a and b (both inclusive)
  swap(input, i, r) // in-place swap
// After the for loop, the selected numbers are at the end of the array
</pre>

O(m) in time, and no additional memory (or O(n) in memory if you want to preserve the original data).

**Comment by shuoh** [comment]
So I found the [source code] (http://svn.python.org/projects/python/branches/pep-382/Lib/random.py) for python's random module:
<pre>
    def shuffle(self, x, random=None, int=int):
        """x, random=random.random -> shuffle list x in place; return None.

        Optional arg random is a 0-argument function returning a random
        float in [0.0, 1.0); by default, the standard random.random.
        """

        randbelow = self._randbelow
        for i in reversed(range(1, len(x))):
            # pick an element in x[:i+1] with which to exchange x[i]
            j = randbelow(i+1) if random is None else int(random() * (i+1))
            x[i], x[j] = x[j], x[i]
</pre>

See, it's basically the solution to our problem given m=n.
