### ISSUE TITLE
AllPairsThatSumToX faster runtime?

### ISSUE THREAD

**Issue by quinnbaetz** [dabaitu/300#9]
Currently the solution assumes you have to return the indices of the integers, but the problem actually asks you to return the integer pairs.  Given this you can solve it not in O(n^2) but O(n log(n)).

1. Create an ordered set -> values  O(n log(n)) and a lookup of counts of each value O(n) 

Then create your solution in O(n) time
2. Have an index at the start and end of your set(sIndex, eIndex),
3. If the int at values[sIndex] + values[eIndex] == searchValue  add (values[sIndex], values[eIndex]) to solution
4.  else If values[sIndex] + values[eIndex] < searchValue then sIndex++
5.  else If values[sIndex] + values[eIndex] > searchValue then eIndex--
6.  if sIndex < eindex go back to step 3
7.  if the value has multiple counts add (values[sIndex], values[sIndex]) to solution
8.  return solution in O(n log(n)) time

Sidenote:  If you need to return multiple pairs of the same ints (e.g (1, 2),(1,2))  this might cause it to be O(n^2).  You would just do
[(values[sIndex], values[eIndex])] * min(count[values[sIndex]],count[values[eIndex]]).  

Does 
    list = ([1] * n)
 run in O(1) or O(n) time in python?

**Comment by cmooney3** [comment]
If you're not concerned about the indicies, can't you do it in O(n) like this

```python
def pairsthatsumtoX(values, x):
  members = set(values)
  results = set([])
  for value in members:
    if (x - value) in members:
      if (value, x - value) not in results:
        results.add(x - value, value)
  return results
```

(btw, check out this: https://guides.github.com/features/mastering-markdown/ it's easy to have github interpret code and syntax hightlight and everything for you by using backticks)

**Comment by cmooney3** [comment]
Oops, I didn't mean to close that.

Also, are you sure you don't need the indicies of the values?  Like, both seem like valid interpretations of it.  I wonder which would be a more common question

**Comment by quinnbaetz** [comment]
That's a great answer charlie!
